name: Deploy to Railway
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Railway
        run: |
          curl -sSL https://railway.app/nix/install | sh
          railway login
          railway up
