name: Secrets

on:
  workflow_dispatch:

jobs:
  top-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get EmailJS Key
        run: echo "The key is ${{ secrets.EMAILKEY }}"
      - name: Unset secret
        run: echo "The unknown secret is ${{ secrets.DOES_NOT_EXIST }}"

        
