name: Secrets

on:
  workflow_dispatch:

env:
  emailjs_secret: ${{ secrets.REACT_APP_EMAILKEY }}

jobs:
  top-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get EmailJS Key
        run: echo "The key is ${{ secrets.REACT_APP_EMAILKEY }}"
      - name: Unset secret
        run: echo "The unknown secret is ${{ secrets.DOES_NOT_EXIST }}"
      - name: Checkout Code
        uses: actions/checkout@v3
      

        
