name: Secrets

on:
  workflow_dispatch:

env:
  REACT_APP_EMAILKEY: ${{ secrets.REACT_APP_EMAILKEY }}

jobs:
  top-secret:
    runs-on: ubuntu-latest
    
     steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies (prod)
        run: yarn install --frozen-lockfile --production

      - name: Run Tests (JEST)
        run: yarn test --ci --silent --testPathIgnorePatterns=experimental
        env:
          CI: true
          API_KEY: ${{ secrets.API_KEY }}
      

        
